# Site wide configuration

title: Annu Yadav
locale: en_US
description: Ruby on Rails developer.
logo: site-logo.jpg
search: true
url: http://annuyadav.github.io

# Jekyll configuration

permalink:   /:categories/:title/
markdown:    kramdown
highlighter: pygments
sass:
  sass_dir: _sass
  style: compressed
gems:
  - jekyll-sitemap

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..2
  use_coderay: false

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules", "Gemfile", "Gemfile.lock", "LICENSE", "README.md", "vendor"]


# Site owner
owner:
  name: Annu Yadav
  avatar: bio-photo.jpg
  email: life.annu.yadav@gmail.com
  disqus-shortname: annuyadav
  twitter: AnnuTheYadav
  facebook: life.annu.yadav
  github: annuyadav
  stackexchange: #http://stackoverflow.com/users/123456/username
  linkedin: lifeannuyadav
  instagram: #username
  flickr: #username
  tumblr: #username
  pinterest: #username
  weibo: #userid
  google:
    plus: AnnuYadavIndispensable
    analytics:
    verify:
    ad-client:
    ad-slot:
  bing-verify:
